apiVersion: v1
kind: Service
metadata:
  name: mlb-schedule-service
spec:
  selector:
    app: mlb-schedule
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlb-schedule
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlb-schedule
  template:
    metadata:
      labels:
        app: mlb-schedule
    spec:
      containers:
      - name: mlb-schedule
        image: mlb-schedule:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
